/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description APIサーバーの稼働状況を確認
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 記事一覧取得
         * @description ページネーション対応の記事一覧を取得
         */
        get: operations["getArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 記事詳細取得
         * @description 指定されたIDの記事詳細を取得
         */
        get: operations["getArticleById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 人気記事一覧取得
         * @description 人気記事の一覧を取得
         */
        get: operations["getPopularArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 最新記事一覧取得
         * @description 最新記事の一覧を取得
         */
        get: operations["getLatestArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * カテゴリ一覧取得
         * @description 全カテゴリの一覧を取得
         */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{slug}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * カテゴリ別記事一覧取得
         * @description 指定されたカテゴリの記事一覧を取得
         */
        get: operations["getArticlesByCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/zenn/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Zenn記事一覧取得
         * @description Zennから最新記事の一覧を取得
         */
        get: operations["getZennArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Article: {
            /**
             * @description 記事ID
             * @example article-123
             */
            ID: string;
            /**
             * @description 記事タイトル
             * @example サンプル記事のタイトル
             */
            Title: string;
            /**
             * Format: uri
             * @description 記事画像URL
             * @example https://images.microcms-assets.io/assets/sample.jpg
             */
            Image: string;
            Category: components["schemas"]["Category"];
            /**
             * @description 記事の概要
             * @example この記事はサンプルの概要です。
             */
            Description: string;
            /**
             * @description 記事本文（HTML形式）
             * @example <p>記事の本文がここに入ります。</p>
             */
            Body: string;
            /**
             * Format: date-time
             * @description 公開日時
             * @example 2023-01-01T00:00:00Z
             */
            PublishedAt: string;
            /**
             * Format: date-time
             * @description 作成日時
             * @example 2023-01-01T00:00:00Z
             */
            CreatedAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             * @example 2023-01-01T00:00:00Z
             */
            UpdatedAt: string;
        };
        Category: {
            /**
             * @description カテゴリスラッグ（ID）
             * @example technology
             */
            Slug: string;
            /**
             * @description カテゴリ名
             * @example テクノロジー
             */
            Name: string;
        };
        Pagination: {
            /**
             * @description 総記事数
             * @example 150
             */
            total?: number;
            /**
             * @description 現在のページ番号
             * @example 1
             */
            page?: number;
            /**
             * @description 1ページあたりの記事数
             * @example 10
             */
            limit?: number;
            /**
             * @description 総ページ数
             * @example 15
             */
            totalPages?: number;
        };
        ArticlesResponse: {
            /** @description 記事リスト */
            articles: components["schemas"]["Article"][];
            pagination?: components["schemas"]["Pagination"];
        };
        ArticleResponse: {
            article: components["schemas"]["Article"];
        };
        CategoriesResponse: {
            /** @description カテゴリリスト */
            categories: components["schemas"]["Category"][];
        };
        ErrorResponse: {
            /**
             * @description エラーメッセージ
             * @example Failed to get articles
             */
            error: string;
            /**
             * @description エラー詳細
             * @example Connection timeout to microCMS API
             */
            detail?: string;
        };
        HealthResponse: {
            /**
             * @description ヘルスチェック結果
             * @example ok
             */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description サーバー正常稼働 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getArticles: {
        parameters: {
            query?: {
                /** @description ページ番号（デフォルト 1） */
                page?: number;
                /** @description 取得件数（デフォルト 10） */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 記事一覧取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlesResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "missing API key"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Failed to get articles",
                     *       "detail": "Connection timeout to microCMS API"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getArticleById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 記事ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 記事詳細取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponse"];
                };
            };
            /** @description リクエストエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Article ID is required"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "invalid API key"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 記事が見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Article not found",
                     *       "detail": "Article with ID 'article-123' does not exist"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Failed to get article",
                     *       "detail": "Connection timeout to microCMS API"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPopularArticles: {
        parameters: {
            query?: {
                /** @description 取得件数（デフォルト 5） */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 人気記事一覧取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlesResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLatestArticles: {
        parameters: {
            query?: {
                /** @description 取得件数（デフォルト 5） */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 最新記事一覧取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlesResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description カテゴリ一覧取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "missing API key"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Failed to get categories",
                     *       "detail": "Connection timeout to microCMS API"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getArticlesByCategory: {
        parameters: {
            query?: {
                /** @description ページ番号（デフォルト 1） */
                page?: number;
                /** @description 取得件数（デフォルト 10） */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description カテゴリスラッグ */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description カテゴリ別記事一覧取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlesResponse"];
                };
            };
            /** @description リクエストエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Category slug is required"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description カテゴリが見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Category not found",
                     *       "detail": "Category with slug 'technology' does not exist"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "error": "Failed to get articles",
                     *       "detail": "Connection timeout to microCMS API"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getZennArticles: {
        parameters: {
            query?: {
                /** @description ページ番号（デフォルト 1） */
                page?: number;
                /** @description 取得件数（デフォルト 10） */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zenn記事一覧取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlesResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
